version: '3'

networks:
  db:
    driver: bridge

services:
  app:
    build: .
    environment:
      DATABASE_HOST: mysqldb
      DATABASE_PORT: 3306
      DATABASE_USER: testing
      DATABASE_PASSWORD: something
      DATABASE_NAME: mentoring_witi

    ports:
      - "4000:4000"
    networks:
      - db
    depends_on:
      - mysqldb
  mysqldb:
    image: mariadb:latest
    environment:
      MARIADB_USER: testing
      MARIADB_DATABASE: mentoring_witi
      MARIADB_PASSWORD: something
      MARIADB_ROOT_PASSWORD: admin
    volumes:
      - ./initdb/initial.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - db
