version: '3'

networks:
  db:
    driver: bridge

services:
  app:
    build: .
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_NAME: mentoring_witi

    ports:
      - "4000:4000"
    networks:
      - db
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:8
    environment:
      MYSQL_USER: root
      MYSQL_DATABASE: mentoring_witi
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./initdb/initial.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - db
